export const AUTHENTICATION_INPROGRESS  = 'AUTHENTICATION_INPROGRESS';
export const LOGIN_SUCCESS              = 'LOGIN_SUCCESS';
export const LOGIN_FAILED    = 'LOGIN_FAILED';
export const UPDATE_TOAST = 'UPDATE_TOAST';
export const RESET_TOAST = 'RESET_TOAST';

//for registration

export const REGISTRATION_SUCCESS='REGISTRATION_SUCCESS';
export const REGISTRATION_FAILED = 'REGISTRATION_FAILED ';

//for Bank transfer

export const BANKTRANSFER_SUCCESS='BANKTRANSFER_SUCCESS';
export const BANKTRANSFER_FAILED = 'BANKTRANSFER_FAILED ';

//for fixed account
export const FIXED_SUCCESS='FIXED_SUCCESS';
export const FIXED_FAILED = 'FIXED_FAILED';

//for current account
export const CURRENT_SUCCESS='CURRENT_SUCCESS';
export const CURRENT_FAILED = 'CURRENT_FAILED';

