export const AUTHENTICATION_INPROGRESS = 'AUTHENTICATION_INPROGRESS';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILED = 'LOGIN_FAILED';
export const UPDATE_TOAST = 'UPDATE_TOAST';
export const RESET_TOAST = 'RESET_TOAST';

//for registration

export const REGISTRATION_SUCCESS = 'REGISTRATION_SUCCESS';
export const REGISTRATION_FAILED = 'REGISTRATION_FAILED ';

//for Agent Transfer

export const AGETTRANSFER_SUCCESS = 'AGETTRANSFER_SUCCESS';
export const AGETTRANSFER_FAILED = 'AGETTRANSFER_FAILED ';

//for Bank transfer

export const BANKTRANSFER_SUCCESS = 'BANKTRANSFER_SUCCESS';
export const BANKTRANSFER_FAILED = 'BANKTRANSFER_FAILED ';

//for fixed account
export const FIXED_SUCCESS = 'FIXED_SUCCESS';
export const FIXED_FAILED = 'FIXED_FAILED';

//for current account
export const CURRENT_SUCCESS = 'CURRENT_SUCCESS';
export const CURRENT_FAILED = 'CURRENT_FAILED';

//for coperative

export const COOPERATIVE_SUCCESS = 'COOPERATIVE_SUCCESS';
export const COOPERATIVE_FAILED = '  COOPERATIVE_FAILED';

// user Account

export const INITIAL_DATA_LOADING = 'INITIAL_DATA_LOADINGA';
export const INITIAL_DATA_FAILED = 'INITIAL_DATA_FAILED';
export const USER_ACCOUNT_CREATE_INPROGRESS = 'USER_ACCOUNT_CREATE_INPROGRESS';
export const USER_ACCOUNT_CREATE_SUCCESS = 'USER_ACCOUNT_CREATE_SUCCESS';
export const USER_ACCOUNT_CREATE_FAILED = 'USER_ACCOUNT_CREATE_FAILED';

//for reset password

export const RESETPASSWORD_SUCCESS = 'RESETPASSWORD_SUCCESS';
export const RESETPASSWORD_FAILED = 'RESETPASSWORD_FAILED';

//for Mpin

export const MPIN_SUCCESS = 'MPIN_SUCCESS';
export const MPIN_FAILED = 'MPIN_FAILED';

//for saving account
export const SAVING_SUCCESS = 'SAVING_SUCCESS';
export const SAVING_FAILED = 'SAVING_FAILED';

//for Apply page and loan type 
export const APPLY_SUCCESS = 'APPLY_SUCCESS';
export const APPLY_FAILED = 'APPLY_FAILED';

//for electricity page
export const ELECTRICITY_SUCCESS = 'ELECTRICITY_SUCCESS';
export const ELECTRICITY_FAILED = 'ELECTRICITY_FAILED';

//for water bill page
export const WATERBILL_SUCCESS = 'WATERBILL_SUCCESS';
export const WATERBILL_FAILED = 'WATERBILL_FAILED';

//for emi calculater page
export const EMI_SUCCESS = 'EMI_SUCCESS';
export const EMI_FAILED = 'EMI_FAILED';

//for flight one way booking page
export const FLIGHTONEWAY_SUCCESS = 'FLIGHTONEWAY_SUCCESS';
export const FLIGHTONEWAY_FAILED = 'FLIGHTONEWAY_FAILED';

